"""Calibrate shock standard deviations to an illustrative FEVD target.

The assignment asks for shock sizes that generate plausible impulse responses and
moments. We make that choice transparent by specifying an illustrative variance-share
target: inflation is mostly driven by cost-push shocks, the policy rate mostly by its
own innovation, and the output gap is split between demand and monetary shocks.

FEVD shares depend only on the products sigma_k^2 * V_k(v), where V_k(v) is the asymptotic
variance of variable v generated by a unit-variance shock k. We compute V_k(v) from the
exact linear-RE solution and then search the shock sizes (anchoring sigma_ex = 0.005) that
best match the target shares at the estimated Chilean calibration.

This is a model-based calibration exercise, not a historical decomposition of Chile and
not an official BCCh target. Outputs: outputs/tables/shock_calibration.csv and
outputs/tables/shock_sigmas.csv.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from scipy.optimize import least_squares

from common import (
    INITIAL_SHOCK_STD,
    TABLES,
    _state_coefficients,
    calibration_rho,
    complete_parameters,
    ensure_directories,
)

VARS = ("x", "pi", "i")
SHOCKS = ("e_x", "e_pi", "e_i")

# Researcher-chosen illustrative shares (per variable, summing to 1).
TARGET = {
    "x": {"e_x": 0.45, "e_pi": 0.10, "e_i": 0.45},
    "pi": {"e_x": 0.02, "e_pi": 0.80, "e_i": 0.18},
    "i": {"e_x": 0.10, "e_pi": 0.15, "e_i": 0.75},
}


def per_shock_variance(params: dict, horizon: int = 4000) -> np.ndarray:
    """V[v, k] = asymptotic variance of variable v from a unit-variance shock k."""
    a_x, a_pi, a_i = _state_coefficients(params)
    sigma, beta, kappa = params["sigma"], params["beta"], params["kappa"]
    rho_i, phi_pi, phi_x = params["rho_i"], params["phi_pi"], params["phi_x"]
    c_i = a_x - (1.0 - a_pi) / sigma
    impact_matrix = np.array(
        [
            [1.0, 0.0, -c_i],
            [-kappa, 1.0, -beta * a_pi],
            [-(1.0 - rho_i) * phi_x, -(1.0 - rho_i) * phi_pi, 1.0],
        ]
    )
    propagation = np.array([a_x, a_pi, a_i])
    variance = np.zeros((3, 3))
    for k in range(3):
        innovation = np.zeros(3)
        innovation[k] = 1.0
        response = np.linalg.solve(impact_matrix, innovation)
        accum = response ** 2
        lag = response[2]
        for _ in range(1, horizon):
            response = propagation * lag
            accum = accum + response ** 2
            lag = response[2]
        variance[:, k] = accum
    return variance


def fevd_from_sigmas(variance: np.ndarray, sigmas: np.ndarray) -> np.ndarray:
    contributions = variance * (sigmas ** 2)  # column k scaled by sigma_k^2
    return contributions / contributions.sum(axis=1, keepdims=True)


def main() -> None:
    ensure_directories()
    params = complete_parameters({"rho_i": calibration_rho()})
    variance = per_shock_variance(params)

    initial_sigmas = np.array(
        [INITIAL_SHOCK_STD["e_x"], INITIAL_SHOCK_STD["e_pi"], INITIAL_SHOCK_STD["e_i"]]
    )
    fevd_initial = fevd_from_sigmas(variance, initial_sigmas)

    target = np.array([[TARGET[v][s] for s in SHOCKS] for v in VARS])

    def residuals(free_log: np.ndarray) -> np.ndarray:
        sigmas = np.array([initial_sigmas[0], np.exp(free_log[0]), np.exp(free_log[1])])
        achieved = fevd_from_sigmas(variance, sigmas)
        return (achieved - target).ravel()

    start = np.log([initial_sigmas[1], initial_sigmas[2]])
    solution = least_squares(residuals, start, method="lm")
    calibrated = np.array(
        [initial_sigmas[0], np.exp(solution.x[0]), np.exp(solution.x[1])]
    )
    fevd_calibrated = fevd_from_sigmas(variance, calibrated)

    rows = []
    for vi, v in enumerate(VARS):
        for si, s in enumerate(SHOCKS):
            rows.append(
                {
                    "variable": v,
                    "shock": s,
                    "fevd_initial_sigmas_pct": 100 * fevd_initial[vi, si],
                    "illustrative_target_pct": 100 * target[vi, si],
                    "fevd_calibrated_sigmas_pct": 100 * fevd_calibrated[vi, si],
                    "calibration_type": "researcher_chosen_model_target",
                }
            )
    table = pd.DataFrame(rows)
    table.to_csv(TABLES / "shock_calibration.csv", index=False)

    sigmas_table = pd.DataFrame(
        {
            "shock": SHOCKS,
            "sigma_initial": initial_sigmas,
            "sigma_calibrated": calibrated,
            "calibration_type": "researcher_chosen_model_target",
        }
    )
    sigmas_table.to_csv(TABLES / "shock_sigmas.csv", index=False)

    print(f"rho_i (Chile baseline) = {params['rho_i']:.4f}")
    print(table.round(2).to_string(index=False))
    print("\nCalibrated sigmas (anchor sigma_ex=0.005):")
    print(sigmas_table.round(5).to_string(index=False))
    print(f"Wrote {TABLES / 'shock_calibration.csv'} and shock_sigmas.csv")


if __name__ == "__main__":
    main()
