"""Calibrate shock standard deviations to two transparent FEVD targets.

The assignment asks for shock sizes that generate plausible impulse responses and
moments. We make that choice transparent by specifying an illustrative variance-share
target: inflation is mostly driven by cost-push shocks, the policy rate mostly by its
own innovation, and the output gap is split between demand and monetary shocks.

FEVD shares depend only on the products sigma_k^2 * V_k(v), where V_k(v) is the asymptotic
variance of variable v generated by a unit-variance shock k. We compute V_k(v) from the
exact linear-RE solution and then search the shock sizes (anchoring sigma_ex = 0.005) that
best match the target shares at the estimated Chilean calibration.

The first target is the didactic benchmark stated in the assignment material. The
second is the researcher's alternative target originally used in this repository.
Neither is a historical decomposition of Chile or an official BCCh estimate.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.optimize import least_squares

from common import (
    FIGURES,
    INITIAL_SHOCK_STD,
    TABLES,
    _state_coefficients,
    calibration_rho,
    complete_parameters,
    ensure_directories,
)

VARS = ("x", "pi", "i")
SHOCKS = ("e_x", "e_pi", "e_i")

TARGETS = {
    "didactic_benchmark": {
        "x": {"e_x": 0.375, "e_pi": 0.100, "e_i": 0.524},
        "pi": {"e_x": 0.014, "e_pi": 0.823, "e_i": 0.162},
        "i": {"e_x": 0.087, "e_pi": 0.147, "e_i": 0.766},
    },
    "researcher_alternative": {
        "x": {"e_x": 0.45, "e_pi": 0.10, "e_i": 0.45},
        "pi": {"e_x": 0.02, "e_pi": 0.80, "e_i": 0.18},
        "i": {"e_x": 0.10, "e_pi": 0.15, "e_i": 0.75},
    },
}


def per_shock_variance(params: dict, horizon: int = 4000) -> np.ndarray:
    """V[v, k] = asymptotic variance of variable v from a unit-variance shock k."""
    a_x, a_pi, a_i = _state_coefficients(params)
    sigma, beta, kappa = params["sigma"], params["beta"], params["kappa"]
    rho_i, phi_pi, phi_x = params["rho_i"], params["phi_pi"], params["phi_x"]
    c_i = a_x - (1.0 - a_pi) / sigma
    impact_matrix = np.array(
        [
            [1.0, 0.0, -c_i],
            [-kappa, 1.0, -beta * a_pi],
            [-(1.0 - rho_i) * phi_x, -(1.0 - rho_i) * phi_pi, 1.0],
        ]
    )
    propagation = np.array([a_x, a_pi, a_i])
    variance = np.zeros((3, 3))
    for k in range(3):
        innovation = np.zeros(3)
        innovation[k] = 1.0
        response = np.linalg.solve(impact_matrix, innovation)
        accum = response ** 2
        lag = response[2]
        for _ in range(1, horizon):
            response = propagation * lag
            accum = accum + response ** 2
            lag = response[2]
        variance[:, k] = accum
    return variance


def fevd_from_sigmas(variance: np.ndarray, sigmas: np.ndarray) -> np.ndarray:
    contributions = variance * (sigmas ** 2)  # column k scaled by sigma_k^2
    return contributions / contributions.sum(axis=1, keepdims=True)


def calibrate_to_target(
    variance: np.ndarray,
    initial_sigmas: np.ndarray,
    target: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, float]:
    """Fit e_pi and e_i standard deviations while anchoring sigma_e_x."""

    target = target / target.sum(axis=1, keepdims=True)

    def residuals(free_log: np.ndarray) -> np.ndarray:
        sigmas = np.array(
            [initial_sigmas[0], np.exp(free_log[0]), np.exp(free_log[1])]
        )
        return (fevd_from_sigmas(variance, sigmas) - target).ravel()

    start = np.log([initial_sigmas[1], initial_sigmas[2]])
    solution = least_squares(residuals, start, method="lm")
    calibrated = np.array(
        [initial_sigmas[0], np.exp(solution.x[0]), np.exp(solution.x[1])]
    )
    achieved = fevd_from_sigmas(variance, calibrated)
    rmse_pp = 100.0 * float(np.sqrt(np.mean((achieved - target) ** 2)))
    return calibrated, achieved, rmse_pp


def plot_comparison(table: pd.DataFrame) -> None:
    fig, axes = plt.subplots(2, 3, figsize=(13, 7), sharey=True)
    labels = {"e_x": "Demand", "e_pi": "Cost-push", "e_i": "Monetary"}
    for row_index, calibration in enumerate(TARGETS):
        subset = table[table["calibration"] == calibration]
        for column_index, variable in enumerate(VARS):
            ax = axes[row_index, column_index]
            frame = subset[subset["variable"] == variable].set_index("shock")
            shocks = list(SHOCKS)
            positions = np.arange(len(shocks))
            ax.bar(
                positions - 0.18,
                frame.loc[shocks, "target_pct"],
                width=0.36,
                label="Target",
                color="#9CA3AF",
            )
            ax.bar(
                positions + 0.18,
                frame.loc[shocks, "achieved_pct"],
                width=0.36,
                label="Achieved",
                color="#1E4E79",
            )
            ax.set_xticks(positions, [labels[shock] for shock in shocks], rotation=20)
            ax.set_title(f"{calibration.replace('_', ' ').title()} - {variable}")
            ax.grid(axis="y", alpha=0.25)
            if column_index == 0:
                ax.set_ylabel("Variance share (%)")
            if row_index == 0 and column_index == 2:
                ax.legend(fontsize=8)
    fig.suptitle("FEVD calibration: stated targets versus model-achieved shares")
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(FIGURES / "fevd_calibration_comparison.png", dpi=180)
    plt.close(fig)


def main() -> None:
    ensure_directories()
    params = complete_parameters({"rho_i": calibration_rho()})
    variance = per_shock_variance(params)

    initial_sigmas = np.array(
        [INITIAL_SHOCK_STD["e_x"], INITIAL_SHOCK_STD["e_pi"], INITIAL_SHOCK_STD["e_i"]]
    )
    fevd_initial = fevd_from_sigmas(variance, initial_sigmas)

    comparison_rows = []
    sigma_rows = []
    fitted: dict[str, np.ndarray] = {}
    for calibration, target_dict in TARGETS.items():
        raw_target = np.array(
            [[target_dict[variable][shock] for shock in SHOCKS] for variable in VARS]
        )
        target = raw_target / raw_target.sum(axis=1, keepdims=True)
        calibrated, achieved, rmse_pp = calibrate_to_target(
            variance, initial_sigmas, target
        )
        fitted[calibration] = calibrated
        for variable_index, variable in enumerate(VARS):
            for shock_index, shock in enumerate(SHOCKS):
                comparison_rows.append(
                    {
                        "calibration": calibration,
                        "variable": variable,
                        "shock": shock,
                        "initial_pct": 100.0 * fevd_initial[variable_index, shock_index],
                        "target_pct": 100.0 * target[variable_index, shock_index],
                        "achieved_pct": 100.0 * achieved[variable_index, shock_index],
                        "difference_pp": 100.0
                        * (
                            achieved[variable_index, shock_index]
                            - target[variable_index, shock_index]
                        ),
                        "rmse_all_shares_pp": rmse_pp,
                        "rho_i": params["rho_i"],
                    }
                )
        for shock, sigma_initial, sigma_calibrated in zip(
            SHOCKS, initial_sigmas, calibrated
        ):
            sigma_rows.append(
                {
                    "calibration": calibration,
                    "shock": shock,
                    "sigma_initial": sigma_initial,
                    "sigma_calibrated": sigma_calibrated,
                    "rho_i": params["rho_i"],
                }
            )

    comparison = pd.DataFrame(comparison_rows)
    sigmas_comparison = pd.DataFrame(sigma_rows)
    comparison.to_csv(TABLES / "fevd_calibration_comparison.csv", index=False)
    sigmas_comparison.to_csv(TABLES / "shock_sigmas_comparison.csv", index=False)
    plot_comparison(comparison)

    # Preserve the original headline outputs for backwards compatibility. The
    # baseline remains the researcher alternative; the benchmark is a robustness case.
    baseline_name = "researcher_alternative"
    baseline = comparison[comparison["calibration"] == baseline_name].copy()
    baseline = baseline.rename(
        columns={
            "initial_pct": "fevd_initial_sigmas_pct",
            "target_pct": "illustrative_target_pct",
            "achieved_pct": "fevd_calibrated_sigmas_pct",
        }
    )
    baseline["calibration_type"] = baseline_name
    baseline[
        [
            "variable",
            "shock",
            "fevd_initial_sigmas_pct",
            "illustrative_target_pct",
            "fevd_calibrated_sigmas_pct",
            "calibration_type",
        ]
    ].to_csv(TABLES / "shock_calibration.csv", index=False)
    pd.DataFrame(
        {
            "shock": SHOCKS,
            "sigma_initial": initial_sigmas,
            "sigma_calibrated": fitted[baseline_name],
            "calibration_type": baseline_name,
        }
    ).to_csv(TABLES / "shock_sigmas.csv", index=False)

    print(f"rho_i (Chile baseline) = {params['rho_i']:.4f}")
    print(comparison.round(3).to_string(index=False))
    print("\nShock-standard-deviation comparison:")
    print(sigmas_comparison.round(6).to_string(index=False))
    print("Wrote FEVD comparison tables and figure.")


if __name__ == "__main__":
    main()
